---
    name: Condition
    on:
      workflow_dispatch: null
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
  
      cheking:
        runs-on: ubuntu-latest
        needs: build
        if: ${{vars.TAUX}} >= 0 and ${{vars.TAUX}} <= 1 
        steps:
          - name: Display
            run: echo "C'est raté"
    