---
    name: Condition 2
    on:
      workflow_dispatch: null
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
  
      cheking:
        runs-on: ubuntu-latest
        needs: build

        steps:
          - name: OK
            if: ${{vars.TAUX >= 0 && vars.TAUX <= 1 }}  
            run: echo "Taux ok"
          - name: Nok
            if: ${{vars.TAUX < 0 || vars.TAUX > 1}} 
            run: echo "Taux nok"
        
      declencheur:
        runs-on: ubuntu-lastest
        needs: build

        steps:
            - uses: actions/setup-python@v2
              with:
                python-version: "3.8"
                
            - name: Recherche du mot cle 'VAGUE'
              env:
                CHERCHE: 0
              run: python recherche.py "${{ github.event.head_commit.message }}"

            - name: Exec
              if: (env.CHERCHE == 1)
              run: echo "j'ai trouvé le mot"
