---
    name: Condition 2
    on:
      workflow_dispatch: null
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
  
      cheking:
        runs-on: ubuntu-latest
        needs: build

        steps:
          - name: OK
            if: ${{vars.TAUX}} >= 0 && ${{vars.TAUX}} <= 1 
            run: echo "Taux ok"
          - name: Nok
            if: ${{vars.TAUX}} < 0 || ${{vars.TAUX}} > 1
            run: echo "Taux nok"
        
        
    